# Recommended set of lints from Flutter team.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Keep code beginner-friendly; do not enforce overly strict rules.
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
